title: Astronomer Alfie
description: The home of out-of-this-world space fun, news and activities.
baseurl: "/astroalf" # MUST match your repo name
url: "https://momquab.github.io"

theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag